### ISSUE TITLE
[platypus] Websocket stream produces garbage under load

### ISSUE THREAD

**Issue by corpix** [cryptounicorns/docs#68]
When we have huge amount of events flying through platypus then it could sometimes(for a 2000/3000 events per second it takes about 4 seconds for bug to appear) produce a broken websocket frames with wrong opcode or other kinds of bullshit.

> https://github.com/corpix/wscp
``` console
$ wscp wss://cryptounicorns.io/api/v1/events/stream 
...
{"type":"changes","payload":{"amount":-0.034599799999999986,"market":"bittrex","percent":-21.344751813389028,"period":"24h","symbolPair":"NXT-USDT","timestamp":1520995945056915700}}
{"type":"changes","payload":{"amount":-18.154697530000007,"market":"bittrex","percent":-21.547400990355207,"period":"24h","symbolPair":"NEO-USDT","timestamp":1520995945056915700}}
~{"type":"changes","payload":{"amount":-0.000023880000000000022,"market":"bittrex","percent":-12.571729402474347,"period":"24h","symbolPair":"VIA-BTC","timestamp":1520995945056915700}}~{"type":"changes","payload":{"amount":-0.0
panic: non-zero rsv bits with no extension negotiated

goroutine 18 [running]:
github.com/corpix/wscp/cli.RootAction.func1(0xc420014d80, 0x971a00, 0xc420113080)
        /build/go/src/github.com/corpix/wscp/cli/root.go:79 +0x304
created by github.com/corpix/wscp/cli.RootAction
        /build/go/src/github.com/corpix/wscp/cli/root.go:63 +0x343
```

**Comment by corpix** [comment]
One more example of this websocket madness:

![image](https://user-images.githubusercontent.com/747362/37467544-75d38896-2858-11e8-85dd-ff58f7247990.png)

**Comment by corpix** [comment]
https://github.com/cryptounicorns/platypus/commit/ab143c1afcc7c41c0dc08ef6dc4960501a94b569 support gorilla websockets and latest changes in queues package.
Added naive stress-test script https://github.com/cryptounicorns/platypus/commit/43fcce8cbf0e36e231f0673ddb581be3f8a2f49b#diff-c44145365a27c376a364272e85e6247fR1, with gorilla I can't reproduce the bug, closing
